### ISSUE TITLE
Restart needed after granted calendar access to display events

### ISSUE THREAD

**Issue by niklasgrewe** [richardtop/CalendarApp#1]
Hi, i am using the latest CK Version. When i start my app the first time, i granted the permission to access my calendar. But after that, CalendarKit is not able to display events. I try to call reloadData() in requestAccessToCalendar() but with now success.

What do i need to change to display events after request access without starting the app again?

**Comment by richardtop** [comment]
Most likely, there is a missing `reloadData` call here: https://github.com/richardtop/CalendarApp/blob/master/Calendar/CalendarViewController.swift#L28

Also, you might need to re-subscribe to the EventStore updates, i.e. invoke this method again:
https://github.com/richardtop/CalendarApp/blob/master/Calendar/CalendarViewController.swift#L32
 Let me know, if any of these suggestions improve the situation and feel free to submit a pull request.

I don't think the CK version matters here, since it's clearly an error in the CalendarApp.

**Comment by niklasgrewe** [comment]
thanks, i tried the following, using the package [SPPermissions](https://github.com/ivanvorobei/SPPermissions):

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    title = "Calendar"
    navigationController?.view.backgroundColor = .systemGray6
    
    if !SPPermissions.Permission.calendar.authorized {
        requestAccessToCalendar()
    } else {
        subscribeToNotifications()
    }
}
```
my `requestAccessToCalendar()` function looks like this:
```swift
func requestAccessToCalendar() {
    let permissions: [SPPermissions.Permission] = [.calendar]
    let controller = SPPermissions.dialog(permissions)
    controller.delegate = self
    controller.present(on: splitViewController ?? self)
}
```
and i implement the callback function like this:
```swift
extension CalendarController: SPPermissionsDelegate {
    func didAllowPermission(_ permission: SPPermissions.Permission) {
        reloadData()
        subscribeToNotifications()
    }
}
```
When i run my app, everthing works without crashing, but i get the following messages in console:
```
[EventKit] Error (1013) in reply block for CADDatabaseFetchCalendarItemsWithPredicate attempt 1/3
[EventKit] Error (1013) in reply block for CADDatabaseFetchCalendarItemsWithPredicate attempt 2/3
[EventKit] Error (1013) in reply block for CADDatabaseFetchCalendarItemsWithPredicate attempt 3/3
[EventKit] All retries exhausted for CADDatabaseFetchCalendarItemsWithPredicate
```

**Comment by niklasgrewe** [comment]
it's a bug. After Permission is granted, you need to create an new `EKEventStore()` like this:

```swift
extension CalendarController: SPPermissionsDelegate {
    func didAllowPermission(_ permission: SPPermissions.Permission) {
        eventStore = EKEventStore() // --> create a new Instance
        reloadData()
        subscribeToNotifications()
    }
}
```

**Comment by richardtop** [comment]
Keeping this open, until I fix this. But if you'd like, I'd appreciate the pull request fixing this issue. Thanks for the investigation!
