### ISSUE TITLE
Is it possible to add a calendar tab or view to an app with a main.storyboard that starts on a different view?

### ISSUE THREAD

**Issue by john1726** [richardtop/CalendarApp#3]
If so, how would I go about doing that?

**Comment by richardtop** [comment]
Yes.
Just show it as a regular UIViewController (programmatically)

These kind of questions are better addressed on stackoverflow.com

**Comment by john1726** [comment]
So for my whole application I am unable to use the UI designer Main.storyboard at all?  Everything must be done programmatically instead?  That makes it much more difficult to build iOS applications with CalendarKit.

**Comment by richardtop** [comment]
Hi, not really.
While I suggest you creating the `DayViewController` in code, you have no limitation of presenting via Storyboard.

Just create an IBAction button and then use this guide to instantiate the CalenarViewController (in code) and show it:
https://developer.apple.com/documentation/uikit/view_controllers/showing_and_hiding_view_controllers

To reiterate, of course you don't have to code all of your application without the storyboard. All you have to do is to implement the calendar in code and then write the code to show it. The rest can be in Storyboard.

Also, it's even possible to create a CalendarKit controller in storyboard, but this is not "officially" supported, so there might be some bugs...
