### ISSUE TITLE
got nil when try to open event

### ISSUE THREAD

**Issue by AkaE41** [richardtop/CalendarApp#5]
when press on event I got nil as he can't cast from EventDescriptor to EkWrapper any help please `
//
//  CalendarViewController.swift
//  Servbud provider
//
//  Created by Khaled on 22/12/2021.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//

import UIKit
import CalendarKit
import EventKit
import EventKitUI
import LKAlertController

protocol CalendarDisplayLogic: AnyObject {
    func displayAvailableTimes(times: [[MainNetworkModels.AvailableTimes]])
    func displayError(errorMessage: String)
    func displayUnAuthorized()
}

class CalendarViewController: DayViewController, CalendarDisplayLogic, EKEventEditViewDelegate {

    // MARK: - Properties

    typealias Models = CalendarModels
    var router: (NSObjectProtocol & CalendarRoutingLogic & CalendarDataPassing)?
    var interactor: CalendarBusinessLogic?
    private var eventStore =  EKEventStore()
    let apiDate = DateFormatter()
    let currentDate = Calendar.current.dateComponents([.year, .month], from: Date())
    var currentmonth = Calendar.current.dateComponents([.year, .month], from: Date()).month
    var allTimes: [MainNetworkModels.AvailableTimes] = []
    var events = [Event]()

    // MARK: - Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: - Setup

    private func setup() {
        let viewController = self
        let interactor = CalendarInteractor()
        let presenter = CalendarPresenter()
        let router = CalendarRouter()

        viewController.router = router
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
    }

    // MARK: - View Lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        apiDate.dateFormat = "yyyy-MM-dd HH:mm:ss"
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        setupUI()
        requestAccessToCalendar()
        view.showActivityView()
        interactor?.getAvailableTimes(month: String(currentDate.month ?? 1), year: String(currentDate.year ?? 2022))
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        events.removeAll()
        allTimes.removeAll()
    }
    
    func setupUI(){
        title = "My Calender"
    }
    
    private func requestAccessToCalendar() {
        // Request access to the events
        eventStore.requestAccess(to: .event) { [weak self] granted, error in
            // Handle the response to the request.
            DispatchQueue.main.async {
                guard let self = self else { return }
                self.initializeStore()
                self.reloadData()
            }
        }
    }
    
    private func initializeStore() {
        eventStore = EKEventStore()
    }
    
    override func eventsForDate(_ date: Date) -> [EventDescriptor] {
        events.removeAll()
        allTimes.forEach { time in
            let fromStringString = (time.from?.date ?? "") + " " + (time.from?.time ?? "")
            let toStringString = (time.to?.date ?? "") + " " + (time.to?.time ?? "")
            let newEvent = Event()
            newEvent.dateInterval = DateInterval(start: apiDate.date(from: fromStringString) ?? Date(), end: apiDate.date(from: toStringString) ?? Date())
            newEvent.isAllDay = false
            newEvent.color = .random
            newEvent.backgroundColor = .random
            newEvent.text = "Avabilty \n from: " + (time.from?.time ?? "") + "to: " + (time.to?.time ?? "")
            newEvent.textColor = .white
            events.append(newEvent)
        }
        return events
    }
    
    // MARK: - DayViewDelegate
    
    // MARK: Event Selection
    
    override func dayViewDidSelectEventView(_ eventView: EventView) {
        guard let ckEvent = eventView.descriptor as? EKWrapper else {
            return
        }
        presentDetailViewForEvent(ckEvent.ekEvent)
    }
    
    private func presentDetailViewForEvent(_ ekEvent: EKEvent) {
        let eventController = EKEventViewController()
        eventController.event = ekEvent
        eventController.allowsCalendarPreview = true
        eventController.allowsEditing = true
        navigationController?.pushViewController(eventController,
                                                 animated: true)
    }
    
    // MARK: Event Editing
    
    override func dayView(dayView: DayView, didLongPressTimelineAt date: Date) {
        // Cancel editing current event and start creating a new one
        endEventEditing()
        let newEKWrapper = createNewEvent(at: date)
        create(event: newEKWrapper, animated: true)
    }
    
    private func createNewEvent(at date: Date, to endDate: Date) -> EKWrapper {
        let newEKEvent = EKEvent(eventStore: eventStore)
        newEKEvent.calendar = eventStore.defaultCalendarForNewEvents
        newEKEvent.startDate = date
        newEKEvent.endDate = endDate
        newEKEvent.title = "Availabilty"
        let newEKWrapper = EKWrapper(eventKitEvent: newEKEvent)
        newEKWrapper.editedEvent = newEKWrapper
        return newEKWrapper
    }
    
    private func createNewEvent(at date: Date) -> EKWrapper {
        let newEKEvent = EKEvent(eventStore: eventStore)
        newEKEvent.calendar = eventStore.defaultCalendarForNewEvents
        
        var components = DateComponents()
        components.hour = 1
        let endDate = calendar.date(byAdding: components, to: date)
        
        newEKEvent.startDate = date
        newEKEvent.endDate = endDate
        newEKEvent.title = "Availabilty"
        
        let newEKWrapper = EKWrapper(eventKitEvent: newEKEvent)
        newEKWrapper.editedEvent = newEKWrapper
        return newEKWrapper
    }
    
    override func dayViewDidLongPressEventView(_ eventView: EventView) {
        guard let descriptor = eventView.descriptor as? EKWrapper else {
            return
        }
        endEventEditing()
        beginEditing(event: descriptor, animated: true)
    }
    
    override func dayView(dayView: DayView, didUpdate event: EventDescriptor) {
        guard let editingEvent = event as? EKWrapper else { return }
        if let originalEvent = event.editedEvent {
            editingEvent.commitEditing()
            
            if originalEvent === editingEvent {
                presentEditingViewForEvent(editingEvent.ekEvent)
            } else {
                
            }
        }
        events.removeAll()
        reloadData()
    }
    
    
    private func presentEditingViewForEvent(_ ekEvent: EKEvent) {
        let eventEditViewController = EKEventEditViewController()
        eventEditViewController.event = ekEvent
        eventEditViewController.eventStore = eventStore
        eventEditViewController.editViewDelegate = self
        present(eventEditViewController, animated: true, completion: nil)
    }
    
    override func dayView(dayView: DayView, didTapTimelineAt date: Date) {
        endEventEditing()
    }
    
    override func dayViewDidBeginDragging(dayView: DayView) {
        endEventEditing()
    }
    
    // MARK: - EKEventEditViewDelegate
    
    func eventEditViewController(_ controller: EKEventEditViewController, didCompleteWith action: EKEventEditViewAction) {
        endEventEditing()
        events.removeAll()
        reloadData()
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        let startDate = dateFormatter.string(from: controller.event?.startDate ?? Date())
        dateFormatter.dateFormat = "HH:mm"
        let startTime = dateFormatter.string(from: controller.event?.startDate ?? Date())
        let endTime = dateFormatter.string(from: controller.event?.endDate ?? Date())
        let sameEventsDay = allTimes.filter { event in
            return event.from?.date == startDate
        }
        var availableTimes = sameEventsDay.map { event -> CalendarModels.availabelTimes in
            let eventFormatter = DateFormatter()
            eventFormatter.dateFormat = "HH:mm:ss"
            let from = dateFormatter.string(from: eventFormatter.date(from: event.from?.time ?? "") ?? Date())
            let to = dateFormatter.string(from: eventFormatter.date(from: event.to?.time ?? "") ?? Date())
            return CalendarModels.availabelTimes(date: event.from?.date, from: from, to: to)
        }
        view.showActivityView()
        if action.rawValue == 1 {
            availableTimes.append(CalendarModels.availabelTimes(date: startDate, from: startTime, to: endTime))
        }
        interactor?.setAvailableTimes(availableTime: availableTimes)
        controller.dismiss(animated: true, completion: nil)
    }
    
    func displayAvailableTimes(times: [[MainNetworkModels.AvailableTimes]]){
        view.hideActivityView()
        allTimes.removeAll()
        times.forEach { item in
            allTimes.append(contentsOf: item)
        }
        events.removeAll()
        reloadData()
    }
    
    func displayError(errorMessage: String) {
        view.hideActivityView()
        showAlert(errorMessage: errorMessage, completion: nil)
    }
    
    func showAlert(errorMessage: String, completion: (( _ choose: Bool) -> Void)?){
        Alert(title: "error", message: errorMessage)
            .addAction("ok", style: .default) { _ in
                completion?(true)
            }
            .show()
    }
    
    func displayUnAuthorized(){
        SharedPrefrences.shared.deconnectUSer()
        router?.goToLogin()
    }
    
    override func dayView(dayView: DayView, willMoveTo date: Date){
        let calendarDate = Calendar.current.dateComponents([.year, .month], from: date)
        if (calendarDate.month != currentmonth) {
            events.removeAll()
            allTimes.removeAll()
            view.showActivityView()
            interactor?.getAvailableTimes(month: String(calendarDate.month ?? 1), year: String(calendarDate.year ?? 2022))
            currentmonth = calendarDate.month
        }
    }

}

`

**Comment by richardtop** [comment]
![image](https://user-images.githubusercontent.com/8013017/172886790-f9c4623d-c953-4243-a4a6-287cea9434fb.jpeg)


It seems that you're passing a different type in eventsForDate, that's why it's impossible to cast to EKWrapper.
