### ISSUE TITLE
New API available for EventKit

### ISSUE THREAD

**Issue by thejipster** [richardtop/CalendarApp#7]
https://developer.apple.com/documentation/technotes/tn3152-migrating-to-the-latest-calendar-access-levels

In IOS 17, a new API is used for calendar Event store access.  Code needs to add in logic to detect that in CalendarViewController.  The new API call is eventStore.requestFullAccessToEvents.  You will also need to add in a new reference in the plist for full access.  **Privacy - Calendar Full Access Usage Description**

private func requestAccessToCalendar() {

        do {

            if #available(iOS 17.0, *) {
                eventStore.requestFullAccessToEvents { [weak self] granted, error in
                    DispatchQueue.main.async {
                        guard let self else { return }
                        self.initializeStore()
                        self.subscribeToNotifications()
                        self.reloadData()
                    }             
            }

            } else {

                eventStore.requestAccess(to: .event) { [weak self] granted, error in
                    // Handle the response to the request.
                    DispatchQueue.main.async {
                        guard let self else { return }
                        self.initializeStore()
                        self.subscribeToNotifications()
                        self.reloadData()
                    }
                }
            }
        }
    }

**Comment by richardtop** [comment]
Would you be able to create a pull request to fix this issue? Both, the code side as well as changing the Info.plist string key? Thanks.

**Comment by thejipster** [comment]
Sorry for the delay.  But glad you got it in there.
