### ISSUE TITLE
Calendar View

### ISSUE THREAD

**Issue by chrmuh** [richardtop/CalendarApp#9]
Hi Richard,

is it possible to use your Tool and the provided Program to program an app that looks like the Samsung calender or like the Ipad calendar but on the iphone. I really like the ipad calendar look but also want to have it on the ipad.

![image](https://github.com/richardtop/CalendarApp/assets/131619916/d1677453-3454-459d-9d73-01c1cde0cb42)

Best wishes
Christopher

**Comment by richardtop** [comment]
Hello Christopher. 
Answering your question: Nope, it is not possible. CalendarKit is a DayView/WeekView only implementation and what you're showing on the screenshot is the month view. Please use the other month view libraries, e.g. https://github.com/airbnb/HorizonCalendar
https://github.com/WenchaoD/FSCalendar

While this indeed is something in-between the Month view and the Week view, I don't think i it's current shape CalendarKit can be customized to display this view. Although, I think it should be on the roadmap and this issue hasn't been created yet.

Feel free to create it with the title "iPad-like month view", as it is very similar to the iPhone week view.

I'm closing this issue, but please ask questions similar to this in the CalendarKIt issues: https://github.com/richardtop/CalendarKit/issues

This issue page is only related to the reference Calendar App implementation as seen in this video: https://www.youtube.com/watch?v=cJ63-_z1qg8

The purpose of the reference implementation is to show how to integrate and build a generic calendar app with the CalendarKit and not to go into the details of the possible customizations.
